#=========================================================================
# Docker Compose File für das Beispieldeployment auf zimolong.eu.
#
# Dadurch können die Studierenden die online bereitgestellten Service
# ntuzen, wenn eine Ausführung auf zwei Computern nicht möglich ist.
#=========================================================================
version: "3.9"

services:
  # Frontend Server
  frontend:
    image: node:20-alpine
    restart: always
    environment:
      LISTEN_HOST:
      LISTEN_PORT: 8000
      GATEWAY_URL: http://zimolong.eu:8010/
    ports:
      # Host:Container
      - 8000:8000
    volumes:
      - ./:/app
    working_dir: /app/frontend
    command: sh -c "npm i; npm start"

  # API-Gateway
  api-gateway:
    image: node:20-alpine
    restart: always
    environment:
      LISTEN_HOST:
      LISTEN_PORT: 8010
    ports:
      # Host:Container
      - 8010:8010
    volumes:
      - ./:/app
    working_dir: /app/api-gateway
    command: sh -c "npm i; npm start"
  
  # Katalog-Backend
  catalogue-backend:
    image: node:20-alpine
    restart: always
    environment:
      LISTEN_HOST:
      LISTEN_PORT: 8020
    ports:
      # Host:Container
      - 8020:8020
    volumes:
      - ./:/app
    working_dir: /app/catalogue-backend
    command: sh -c "npm i; npm start"
  
  # Auftrags-Backend
  order-backend:
    image: node:20-alpine
    restart: always
    environment:
      LISTEN_HOST:
      LISTEN_PORT: 8030
    ports:
      # Host:Container
      - 8030:8030
    volumes:
      - ./:/app
    working_dir: /app/order-backend
    command: sh -c "npm i; npm start"